# Generated by Django 4.2.11 on 2024-04-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(default='default_url', verbose_name='Image URL:'),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
